// Class: kha.CompilerDefines

var $global = typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this

$global.Object.defineProperty(exports, "__esModule", {value: true});

var __map_reserved = {};

// Imports

var $hxClasses = require("./../hxClasses_stub").default;

// Constructor

var CompilerDefines = function(){}

// Meta

CompilerDefines.__name__ = ["kha","CompilerDefines"];
CompilerDefines.prototype = {
	
};
CompilerDefines.prototype.__class__ = CompilerDefines.prototype.constructor = $hxClasses["kha.CompilerDefines"] = CompilerDefines;

// Init



// Statics


CompilerDefines.hxgenjs = "0.4.1"
CompilerDefines.js = "1"
CompilerDefines.kha_a1 = "1"
CompilerDefines.kha_g3 = "1"
CompilerDefines.kha_html5_js = "1"
CompilerDefines.source-header = "Generated by Haxe 3.4.7"
CompilerDefines.jquery_ver = "11204"
CompilerDefines.kha_js = "1"
CompilerDefines.sys_html5 = "1"
CompilerDefines.sys_g4 = "1"
CompilerDefines.tink_core = "1.17.0"
CompilerDefines.no_inline = "1"
CompilerDefines.sys_g2 = "1"
CompilerDefines.kha_webgl = "1"
CompilerDefines.tsextern = "1"
CompilerDefines.kha = "1"
CompilerDefines.kha_g2 = "1"
CompilerDefines.kha_g4 = "1"
CompilerDefines.sys_g3 = "1"
CompilerDefines.tink_macro = "0.16.6"
CompilerDefines.kha_g1 = "1"
CompilerDefines.sys_a1 = "1"
CompilerDefines.haxe_ver = "3.407"
CompilerDefines.canvas_id = "khanvas"
CompilerDefines.kha_version = "1611"
CompilerDefines.js_es = "5"
CompilerDefines.kha_html5 = "1"
CompilerDefines.js-es5 = "1"
CompilerDefines.js_es5 = "1"
CompilerDefines.sys_a2 = "1"
CompilerDefines.dce = "std"
CompilerDefines.sys_g1 = "1"
CompilerDefines.true = "1"
CompilerDefines.haxe3 = "1"
CompilerDefines.kha_a2 = "1"
CompilerDefines.script_name = "kha"

// Export

exports.default = CompilerDefines;